version: '2'
services:
  zookeeper1:
    build: base-kafka
    command: zookeeper 1
  zookeeper2:
    build: base-kafka
    command: zookeeper 2
  zookeeper3:
    build: base-kafka
    command: zookeeper 3

  kafka:
    build: base-kafka
    command: kafka
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3

  # kafka_manager:
  #   image: sheepkiller/kafka-manager
  #   environment:
  #     ZK_HOSTS: "zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
  #   ports:
  #     - 9000:9000
  #   depends_on:
  #     - zookeeper1
  #     - zookeeper2
  #     - zookeeper3
  #     - kafka